### ISSUE TITLE
FFImageLoading.Forms: Invalid scale for images in iOS

### ISSUE THREAD

**Issue by marlonconstante** [luberda-molinet/FFImageLoading#349]
Problem is occurring in the latest release: 2.2.0.
In version 2.1.8 it worked perfectly on both platforms (iOS and Android).
Currently the expected result is presented only on Android, but not on iOS.

This problem has already occurred previously
[https://github.com/luberda-molinet/FFImageLoading/issues/222] and was solved here [https://github.com/luberda-molinet/FFImageLoading/commit/44b0f32cac95e0bbe0061f7a6f97061c3c97f3b2]

**Comment by daniel-luberda** [comment]
@marlonconstante  Could you test newest alpha and check if it's solved? Thanks.

**Comment by marlonconstante** [comment]
Unfortunately the problem has not been solved = (

The following screen print comparing versions for better understanding:

![screen](https://cloud.githubusercontent.com/assets/6370612/19888212/62a0e8a4-a014-11e6-9c3f-5bc183da82ce.png)

**Comment by marlonconstante** [comment]
I believe the problem is this code snippet:

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/DataResolvers/FileDataResolver.cs#L36-L39

**Comment by daniel-luberda** [comment]
Yes, I missed that. I'll release new version today which will fix this.

**Comment by daniel-luberda** [comment]
Nuget with fix released.

**Comment by marlonconstante** [comment]
@daniel-luberda Unfortunately the problem is still occurring in version _2.2.2_

**Comment by shnaz** [comment]
Same problem here. using 2.2.2..

**Comment by marlonconstante** [comment]
To work right for now I'm using this workaround in my image class that inherits from CachedImage:

```c#
protected override void OnPropertyChanged(string propertyName = null)
{
	if (Device.OS == TargetPlatform.iOS)
	{
		if (propertyName == nameof(Source) && Source is FileImageSource)
		{
			var file = (Source as FileImageSource).File;
			var fileName = Path.GetFileNameWithoutExtension(file);
			var extension = Path.GetExtension(file);
			var scale = (int) Display.GetScale();

			if (scale > 1 && !fileName.Contains($"@{scale}x"))
			{
				Source = string.Format("{0}@{1}x{2}", fileName, scale, extension);
				return;
			}
		}
	}

	base.OnPropertyChanged(propertyName);
}
```

**Comment by daniel-luberda** [comment]
@marlonconstante Thanks for the workaround. I'll try to debug it once again. Sorry for that, the amount of changes were huge in this release, so I could have missed something.

**Comment by daniel-luberda** [comment]
Could you try 2.2.3 prerelease? It should be fixed.

**Comment by marlonconstante** [comment]
Worked perfectly!
Thanks

**Comment by ianjonesau** [comment]
Still experiencing, under iOS, the invalid scale and image ignoring @2x/@3x issues?
Using v2.2.7 - just wondering if this is still a known issue?

**Comment by daniel-luberda** [comment]
@ianjonesau No it isn't, could you give more details?

**Comment by ianjonesau** [comment]
Daniel,

Firstly, thanks for responding - loving the library!

I've attached three (3) screenshots where I've used one of my existing
Xamarin.Forms app launch screens.
They show the oversize image from the CachedImage control, as well as the
low quality only improving if I specifically put the @2x or @3x in the file
name.

The oversize image is a common problem I've got everywhere (toolbar images,
row images, etc).
I found that I needed to put specific sizes on each image after this
problem started manifesting a few months ago.

The other issue is the image quality on iOS.

Test code is :-

var facebookButton = new CachedImage()
{
HorizontalOptions = LayoutOptions.CenterAndExpand,
VerticalOptions = LayoutOptions.CenterAndExpand,
Aspect = Aspect.AspectFit,
Source = "Images/facebook@3x.png",
};
var facebookButton2 = new Image()
{
HorizontalOptions = LayoutOptions.CenterAndExpand,
VerticalOptions = LayoutOptions.CenterAndExpand,
Aspect = Aspect.AspectFit,
Source = "Images/facebook.png",
};

Images/facebook.png (blurry image)
[image: Inline images 1]

Images/facebook@2x.png :-
[image: Inline images 2]

Images/facebook@3x.png :-
[image: Inline images 3]

Kind Regards,
Ian

Ian Jones
m 0417 297 213
e ianjones@pobox.com

**Comment by daniel-luberda** [comment]
Thanks :) Could you attach those images once again? I didn't receive them.

**Comment by ianjonesau** [comment]
Sure - the screenshots are now attached.
Also attached are the images used in the project.
Kind Regards,
Ian


Ian Jones
m 0417 297 213
e ianjones@pobox.com

**Comment by ianjonesau** [comment]
Daniel,

Realised I broke my own rules - code snippets aren't much help - sorry :(
Here is a 'solution > new' Xamarin forms sample app with CachedImage and
Image controls using FFimage v2.2.7 that manifests the issues.

Sizing issue appears to affect iOS and Android (it used to appear just like
built in XF.Image control).
Quality issue (@2x/@3x) just iOS.

Fully working sample - trust this is more helpful !

Kind Regards,
Ian

Ian Jones
m 0417 297 213
e ianjones@pobox.com

**Comment by daniel-luberda** [comment]
@ianjonesau Sure, but you'll need to send it directly to my email (it's on my github profile) as github doesn't support attachments.

**Comment by daniel-luberda** [comment]
Hi @ianjonesau, 

I reviewed you example quickly (didn't have time to give it a more detailed look yet): 

- On iOS, you must put `Image` folder to `Resources` folder. That way correct images sizes are used. This was the reason `@2x`, `@3x` sizes didn't work. 
- As to oversizing, FFImageLoading always uses whole view size. If you don't want to fill whole space, just don't use `Fill` / `Expand` layout options or layouts which expand all its children by default. Please try to replace `CachedImage` with `BoxView` with some background colour, coloured area will always be used as image area. Here's method responsible for this: 
  - `CachedImage`: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/CachedImage.cs#L490-L523
  - `Image`: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Image.cs#L62-L118

**Comment by ianjonesau** [comment]
Daniel,
Thanks - big help.
I though you just needed to flag images as EmbeddedResources - didn't
realise the default location was essential as well.
Kind Regards,
Ian

Ian Jones
m 0417 297 213
e ianjones@pobox.com

**Comment by chrux** [comment]
Guys I still have this issue
```<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="harmons.Views.MyPageView" xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms">
  <ContentPage.Content>
		<StackLayout HorizontalOptions="FillAndExpand" BackgroundColor="Fuchsia">
		  <ffimageloading:CachedImage Source="btn_pharmacy_text.png" VerticalOptions="Center" HorizontalOptions="Center" />
			<Image Source="btn_pharmacy_text.png" VerticalOptions="Center" HorizontalOptions="Center" />
		</StackLayout>
  </ContentPage.Content>
</ContentPage>
```
![image1](https://cloud.githubusercontent.com/assets/610949/26015206/475c58bc-371d-11e7-988d-621d05433a52.JPG)

**Comment by chrux** [comment]
BTW I am using version 2.2.9

**Comment by daniel-luberda** [comment]
@chrux See this: https://github.com/luberda-molinet/FFImageLoading/issues/480

**Comment by mariuszdybala** [comment]
I have the same issue like @chrux - ver 2.2.9
