### ISSUE TITLE
FFImageLoading fail to load image on iOS after upgrading from 2.1.8 to 2.2.4

### ISSUE THREAD

**Issue by buttifabio** [luberda-molinet/FFImageLoading#365]
Hi,

I have a Xamarin.Forms project where i use FFImageLoading to load an image from a web url applying a CircleTransformation.

This is the init code:
```
Image = new CachedImage {
	Aspect = Aspect.AspectFill,
	HorizontalOptions = LayoutOptions.CenterAndExpand,
	VerticalOptions = LayoutOptions.CenterAndExpand,
	CacheDuration = TimeSpan.FromDays (30),
	DownsampleUseDipUnits = true,
	DownsampleWidth = size,
	LoadingPlaceholder = DefaultImage,
	ErrorPlaceholder = DefaultImage,
	Transformations = new System.Collections.Generic.List<ITransformation> () {
		new CircleTransformation(),
	},
	TransformPlaceholders = true
};
```

When i download the data model from my webservice i setup `Image.Source = "https://censored/url/of/image.jpg"`.

With FFIMageLoading.iOS 2.1.8 everything worked, but after the upgrade to 2.2.4 i have the following exceptions:
`Image loading failed: https://censored/url/of/image.jpg;188x0CircleTransformation,borderSize=0,borderHexColor=
System.Exception: Could not initialize an instance of the type 'UIKit.NSDataAsset': the native 'initWithName:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false.`
and
`Image loading failed: https://censored/url/of/image.jpg;188x0CircleTransformation,borderSize=0,borderHexColor=
UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.`

I attach a file with the full stack trace.
Thank you for you help.

[FFImageLoading_upgrade_error.txt](https://github.com/luberda-molinet/FFImageLoading/files/575814/FFImageLoading_upgrade_error.txt)

**- Edit -**
I also tried removing the CircleTransformation but the issue wasn't there.

**Comment by Spierki** [comment]
+1

**Comment by daniel-luberda** [comment]
Hi @buttifabio,

- What version of iOS?

**Comment by Spierki** [comment]
@daniel-luberda 10.0.2 for me

**Comment by buttifabio** [comment]
@daniel-luberda 10.1.1

**Comment by daniel-luberda** [comment]
@buttifabio @Spierki 

Could you test the newest pre-nuget and notify me if it's fixed?

**Comment by buttifabio** [comment]
@daniel-luberda 

I downgrade to 2.2.3 and the error changed to
[FFImageLoading_error_version_2.2.3.txt](https://github.com/luberda-molinet/FFImageLoading/files/577559/FFImageLoading_error_version_2.2.3.txt)

It's strange because `user_avatar_default.png` is present in the bundle. In fact if i downgrade to 2.1.8 again everything works.

**Comment by Spierki** [comment]
@daniel-luberda not working for the last pre-nuget, this is the error : 

> Image loading failed: /var/mobile/Containers/Data/Application/F9D7F379-693C-476A-B960-B6864ECB5CA6/Documents/cartesFidelite/c78a2a15-c2ca-4ede-9cad-34ee18c08883.jpg;100x0
System.IO.FileNotFoundException: /var/mobile/Containers/Data/Application/F9D7F379-693C-476A-B960-B6864ECB5CA6/Documents/cartesFidelite/c78a2a15-c2ca-4ede-9cad-34ee18c08883.jpg
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x003ef] in <9ef0b80610e246fa9936690e1e1d0e0d>:0 `

**Comment by daniel-luberda** [comment]
Coukd you test 2.2.5-pre-207?

**Comment by timbrand** [comment]
Seems that I'm having this issue too.
On 2.2.4 it gave me an exception the "UIKit.UIKitThreadAccessException". Then I updated to the pre-207 nuget and now getting the following exception:
`Image loading failed: /var/mobile/Containers/Data/Application/0D32FC7C-735A-4567-9D07-462C027125CC/Documents/temp/IMG_20161108_213433.jpg;200x0
System.IO.FileNotFoundException: /var/mobile/Containers/Data/Application/0D32FC7C-735A-4567-9D07-462C027125CC/Documents/temp/IMG_20161108_213433.jpg
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x00401] in <8a55c00e115949e79957138270bb8e66>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <a11ea1906afa4ff781670d3ba1c4a833>:0 
  at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__104[TImageContainer,TImageView].MoveNext () [0x00270] in <75f69755386b4a978f988204d7da532a>:0 `

**Comment by buttifabio** [comment]
@daniel-luberda 

Excuse me, but how can i test versione 2.2.5-pre-207? Where can i get that version?

Thank you

**Comment by mike-rowley** [comment]
@buttifabio the prereleases are all on Nuget.
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.2.5-pre-207

Note: you may need check off "Include Prereleases" if you are using the Nuget Manager in Visual Studio.

**Comment by daniel-luberda** [comment]
Could you test the newest 2.2.5-pre-209 alpha? It should be fixed (I hope so).

**Comment by timbrand** [comment]
Sorry, still not working. Even tried the 212 build, also not working.

Exception I get on the 212-build:

`016-11-10 20:37:07.547 GroupComiOS[293:51154] Image loading failed: /var/mobile/Containers/Data/Application/E8582598-4DA0-4416-A322-EB09497C9BB9/Documents/temp/IMG_20161110_203706-2280x2280.jpg;200x0
System.IO.FileNotFoundException: /var/mobile/Containers/Data/Application/E8582598-4DA0-4416-A322-EB09497C9BB9/Documents/temp/IMG_20161110_203706-2280x2280.jpg
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x003f5] in <a54e306f77d44cb791e6de3ee3d25f2f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <a11ea1906afa4ff781670d3ba1c4a833>:0 
  at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__104[TImageContainer,TImageView].MoveNext () [0x00278] in <c73678e7ea17480e9de1f6e0cfd58cfa>:0 `

**Comment by daniel-luberda** [comment]
Arrgh.... @timbrand Could you make a repro, so I could finally fix this? I can't reproduce it.

**Comment by daniel-luberda** [comment]
I hope it's the last fix :)

**Comment by timbrand** [comment]
Sorry, still not fixed. I'll now create a project to reproduce it.

**Comment by timbrand** [comment]
You can use this project to reproduce the issue.

[ffimageloading_test.zip](https://github.com/luberda-molinet/FFImageLoading/files/586005/ffimageloading_test.zip)

**Comment by marra85** [comment]
@daniel-luberda 

Hello,
I think I'm still hitting this issue with both versions 2.2.5  and 2.2.6-pre-228 .
the image "icn_eno.png" is a bundleresource. 

`
2016-11-13 16:18:50.699 DOTMobileiOS[967:44563] Image loading failed: icn_eno.png
System.IO.FileNotFoundException: icn_eno.png
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x00512] in <2dad20202474493fb6cd0d6a3500e7ec>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable ``1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at FFImageLoading.Work.ImageLoaderTask``2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x00278] in <14f599d1536e4c14b0ae7cd38663433b>:0 
2016-11-13 16:18:50.699 DOTMobileiOS[967:44542] Image loading failed: icn_eno.png
`

**Comment by daniel-luberda** [comment]
@marra85 Can you make a reproduction? Not enough info.

**Comment by timbrand** [comment]
In my case I can confirm that the issue has been resolved in the latest pre-228 release.
Thanks for that!!

**Comment by marra85** [comment]
@daniel-luberda 

Sorry, it was a git problem (the resources were not tracked in git so they weren't available in my test branch).

**Comment by raphaelcr93** [comment]
Hello,

Just got it in version 2.2.7

When using in LoadingPlaceholder attribute some file that did not exist in my resources.

For example:

LoadingPlaceholder = "loadingImageThatDoesNotExist.png"

**Comment by aphex3k** [comment]
I see the same issue using version 2.2.9 throwing UIKitThreadAccessException on iOS 10

**Comment by daniel-luberda** [comment]
@aphex3k Please use the newest prerelease (it was fixed)
