### ISSUE TITLE
Android.OS.NetworkOnMainThreadException thrown

### ISSUE THREAD

**Issue by elertan** [luberda-molinet/FFImageLoading#416]
The problem is that while scrolling a listview (FlowListView in my case) the images I download from the internet and cache using a CachedImage in my xaml page throws a NetworkOnMainThreadException as InnerException of an AggregateException. Ive done some research about whats happening and it seems that its exactly what the exception name says it is. So that means that FFImageLoading is doing some sort of network activity on the mainthread when I start requesting a lot of images. This is not happening on iOS, that works just fine. Any thoughts on this?

**Comment by softlion** [comment]
+1, it is only when using AndroidClientHandler instead of HttpClientHandler.

It can be easily reproduced by running the "heavy list" sample with the latest stable xamarin version.

The problem seems to lie in CachedImageRenderer.cs in the Cancel() method. The cancellation must not be called on the main thread otherwise android crashes with NetworkOnMainThreadException when it closes the socket.

		private void Cancel()
		{
			if (_currentTask != null && !_currentTask.IsCancelled) 
			{
				_currentTask.Cancel();
			}
		}

must be replaced by

		private void Cancel()
		{
			if (_currentTask != null && !_currentTask.IsCancelled) 
			{
				Device.BeginInvokeOnMainThread(() => _currentTask.Cancel());
			}
		}

**Comment by elertan** [comment]
@softlion Okay, that makes sense. Thanks for responding so quickly. Since the developer of FFImageLoading seems inactive for a while I doubt this will be implemented soon. Do you have any good solution for now? Such as using a custom android CachedImageRenderer that has the right code. Thanks alot, it's really appreciated!

**Comment by softlion** [comment]
No solution, just stumbled upon the problem today too, while working on TLS 1.2 support. I forked and fixed the repo, but my customer does not have time for this so i don't have too. Btw ffmimageloading has some other bad bugs it seems (i'm quite new at using it). Caching seems to malfunction for example. I have my own private ffimageloading like control but not for xamarin forms currently. So i hope the repo owner will wake up ;)

**Comment by daniel-luberda** [comment]
@elertan @softlion It's fixed now. 

@softlion 
> Caching seems to malfunction for example.

Can you give more details about it, so we could fix that?

**Comment by allbdeveloper** [comment]
@softlion 
Hi, I'm making app with using XF pcl. (2.3.3.180)
I saw this. https://bugzilla.xamarin.com/show_bug.cgi?id=44961
But I'm still facing this exception unless I use Task.run. 
Can you give me any idea?

**Comment by softlion** [comment]
Well it should not be the same problem as it is fixed.

**Comment by allbdeveloper** [comment]
@softlion 
Hm, but exception message is same and workaround that is wrapping with Task.run to fix this issue is same. 
Oh, I found this, https://github.com/xamarin/xamarin-android/pull/247
and this says it will be included on Xamarin.android 7.1, which is currently 7.0.2.42.
So it's not merged yet on the stable release.
Am I correct?
