### ISSUE TITLE
Runtime-error/unhandled exception

### ISSUE THREAD

**Issue by quakeulf** [luberda-molinet/FFImageLoading#625]
> Unhandled Exception:
> 
> FreshTinyIoC.TinyIoCResolutionException: Resolve failed: SettingsPage - Reason: Could not resolve type with token 0100004f (from typeref, class/assembly FFImageLoading.Svg.Forms.SvgCachedImage, FFImageLoading.Svg.Forms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

Just a little over an hour ago I updated to the latest prerelease version to fix SvgCachedImage, but every time I build the app I get this error now.

This is how it looks like in the XAML:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Smiley.Pages.SettingsPage"
             Title="{Binding Title}">
```
And where it gets used:
```
 <ffimageloadingsvg:SvgCachedImage 
                        Grid.Row="0"
                        Grid.Column="0"
                        WidthRequest="16" 
                        HeightRequest="40" 
                        Source="sidepil.svg"/>
```
What am I doing wrong? Please help.

**Comment by daniel-luberda** [comment]
Xamarin Linker cuts it.

- It should be fixed in upcoming nuget
- OR Just reference `SvgCachedImage` somewhere in your platform specific code (Eg. ` var ignore = new SvgCachedImage()`), etc

**Comment by quakeulf** [comment]
Ok, the error is no longer appearing but I still don't get a visible SVG. Maybe it's something else causing this, lol.
